"""empty message

Revision ID: 1e5dce0cf4b2
Revises: 
Create Date: 2019-09-26 20:04:07.932860

"""
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# pylint: disable=no-member
# pylint: disable=bad-continuation
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5dce0cf4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber',
        sa.Column('email', sa.String(length=50), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=False),
        sa.Column('password', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barber')
    # ### end Alembic commands ###
