"""empty message

Revision ID: 613d6cd31949
Revises: 1e5dce0cf4b2
Create Date: 2019-10-04 06:58:08.738359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613d6cd31949'
down_revision = '1e5dce0cf4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('status', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barber', 'status')
    # ### end Alembic commands ###
